spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:file:~/java14
        username: sa
        data: classpath*:db/init.sql
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        hibernate:
            ddl-auto: 'create-drop'
            show_sql: true
            format_sql: true
            type: trace
